export const GET_MAPPED_BRICKS = 'GET_MAPPED_BRICKS';
export const GET_MAPPED_BRICKS_SUCCESS = 'GET_MAPPED_BRICKS_SUCCESS';
export const GET_MAPPED_BRICKS_FAILURE = 'GET_MAPPED_BRICKS_FAILURE';

export const REQUEST_BRICK_MAPPING = 'REQUEST_BRICK_MAPPING'
export const REQUEST_BRICK_MAPPING_SUCCESS = 'REQUEST_BRICK_MAPPING_SUCCESS'
export const REQUEST_BRICK_MAPPING_FAILURE = 'REQUEST_BRICK_MAPPING_FAILURE'


export const GET_REQUESTED_MAPPINGS = 'GET_REQUESTED_MAPPINGS'
export const GET_REQUESTED_MAPPINGS_SUCCESS = 'GET_REQUESTED_MAPPINGS_SUCCESS'
export const GET_REQUESTED_MAPPINGS_FAILURE = 'GET_REQUESTED_MAPPINGS_FAILURE'
