export const GET_DECLINING_CONSG_OUTLETS = 'GET_DECLINING_CONSG_OUTLETS';
export const GET_DECLINING_CONSG_OUTLETS_SUCCESS = 'GET_DECLINING_CONSG_OUTLETS_SUCCESS';
export const GET_DECLINING_CONSG_OUTLETS_FAILURE = 'GET_DECLINING_CONSG_OUTLETS_FAILURE';

export const SUBMIT_OUTLET_REVIEW = 'SUBMIT_OUTLET_REVIEW'
export const SUBMIT_OUTLET_REVIEW_SUCCESS = 'SUBMIT_OUTLET_REVIEW_SUCCESS'
export const SUBMIT_OUTLET_REVIEW_FAILURE = 'SUBMIT_OUTLET_REVIEW_FAILURE'