export const GET_CALLS = 'GET_CALLS'
export const GET_CALLS_SUCCESS = 'GET_CALLS_SUCCESS'
export const GET_CALLS_FAILURE = 'GET_CALLS_FAILURE'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

