/*
* Auth actions 
*/
export const LOGIN = 'LOGIN'
export const LOGIN_CHECK = 'LOGIN_CHECK'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

/**
* Calls Action 
**/
export const GET_CALLS = 'GET_CALLS'
export const GET_CALLS_SUCCESS = 'GET_CALLS_SUCCESS'
export const GET_CALLS_FAILURE = 'GET_CALLS_FAILURE'
export const SUBMIT_CALL = 'SUBMIT_CALL'
export const SUBMIT_CALL_SUCCESS = 'SUBMIT_CALL_SUCCESS'
export const SUBMIT_CALL_FAILURE = 'SUBMIT_CALL_FAILURE'
export const GET_UNPLANNED_CALLS = 'GET_UNPLANNED_CALLS'
export const GET_UNPLANNED_CALLS_SUCCESS = 'GET_UNPLANNED_CALLS_SUCCESS'
export const GET_UNPLANNED_CALLS_FAILURE = 'GET_UNPLANNED_CALLS_FAILURE'

/** 
 * Gifts actions
 **/
export const GET_GIFTS = 'GET_GIFTS'
export const GET_GIFTS_SUCCESS = 'GET_GIFTS_SUCCESS'
export const GET_GIFTS_FAILURE = 'GET_GIFTS_FAILURE'


/** 
 * Products Actions 
 **/
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

/** 
 * History Actions 
 **/
export const GET_HISTORY = 'GET_HISTORY'
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS'
export const GET_HISTORY_FAILURE = 'GET_HISTORY_FAILURE'

/** 
 * DoctorDesignation Actions 
 **/
export const GET_DOCTOR_DESIGNATION = 'GET_DOCTOR_DESIGNATION'
export const GET_DOCTOR_DESIGNATION_SUCCESS = 'GET_DOCTOR_DESIGNATION_SUCCESS'
export const GET_DOCTOR_DESIGNATION_FAILURE = 'GET_DOCTOR_DESIGNATION_FAILURE'

/** 
 * DOCTOR_SPECIALITY Actions 
 **/
export const GET_DOCTOR_SPECIALITY = 'GET_DOCTOR_SPECIALITY'
export const GET_DOCTOR_SPECIALITY_SUCCESS = 'GET_DOCTOR_SPECIALITY_SUCCESS'
export const GET_DOCTOR_SPECIALITY_FAILURE = 'GET_DOCTOR_SPECIALITY_FAILURE'

/** 
 * DOCTOR_REQUEST Actions 
 **/
export const SUBMIT_DOCTOR_REQUEST = 'SUBMIT_DOCTOR_REQUEST'
export const SUBMIT_DOCTOR_REQUEST_SUCCESS = 'SUBMIT_DOCTOR_REQUEST_SUCCESS'
export const SUBMIT_DOCTOR_REQUEST_FAILURE = 'SUBMIT_DOCTOR_REQUEST_FAILURE'

/** 
 * CITY Actions
 **/
export const GET_CITIES = 'GET_CITIES'
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS'
export const GET_CITIES_FAILURE = 'GET_CITIES_FAILURE'

/** 
 * GET DOCTOR BY EMPLOYEE Actions
 **/
export const GET_DOCTORS_BY_EMPLOYEE = 'GET_DOCTORS_BY_EMPLOYEE'
export const GET_DOCTORS_BY_EMPLOYEE_SUCCESS = 'GET_DOCTORS_BY_EMPLOYEE_SUCCESS'
export const GET_DOCTORS_BY_EMPLOYEE_FAILURE = 'GET_DOCTORS_BY_EMPLOYEE_FAILURE'

/** 
 * GET REPORTING EMPLOYEES Actions
 **/
export const GET_REPORTING_EMPLOYEES = 'GET_REPORTING_EMPLOYEES'
export const GET_REPORTING_EMPLOYEES_SUCCESS = 'GET_REPORTING_EMPLOYEES_SUCCESS'
export const GET_REPORTING_EMPLOYEES_FAILURE = 'GET_REPORTING_EMPLOYEES_FAILURE'
