/** 
 * DOCTOR_REQUEST Actions 
 **/
export const SUBMIT_DOCTOR_REQUEST = 'SUBMIT_DOCTOR_REQUEST'
export const SUBMIT_DOCTOR_REQUEST_SUCCESS = 'SUBMIT_DOCTOR_REQUEST_SUCCESS'
export const SUBMIT_DOCTOR_REQUEST_FAILURE = 'SUBMIT_DOCTOR_REQUEST_FAILURE'

export const GET_PENDING_DOCTOR_REQUESTS = 'GET_PENDING_DOCTOR_REQUESTS'
export const GET_PENDING_DOCTOR_REQUESTS_SUCCESS = 'GET_PENDING_DOCTOR_REQUESTS_SUCCESS'
export const GET_PENDING_DOCTOR_REQUESTS_FAILURE = 'GET_PENDING_DOCTOR_REQUESTS_FAILURE'